<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>

    <!-- Metadati per il pacchetto NuGet -->
    <PackageId>Lifter.Blazor</PackageId>
    <Version>2.0.0</Version>
    <Authors>Luca Fabbri</Authors>
    <PackageContact>lucafabbri84@live.it</PackageContact>
    <Copyright>Copyright (c) Luca Fabbri 2026</Copyright>
    <Description>
      .NET Blazor WebAssembly integration for Lifter. This package enables IHostedService support in .NET Blazor WebAssembly applications,
      allowing for long-running background tasks managed by the app lifecycle.
    </Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/lucafabbri/Lifter</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lucafabbri/Lifter</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>blazor;blazor-webassembly;hostedservices;background;service;host;lifter;core</PackageTags>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <!-- Configurazione per SourceLink -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lifter.Core\Lifter.Core.csproj" />
  </ItemGroup>



</Project>
