<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <IsPackable>false</IsPackable>
    <UserSecretsId>df5bbda5-3540-4f16-a14f-2dfcdb84747a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapBlazor" Version="10.6.0" />
    <PackageReference Include="BootstrapBlazor.FontAwesome" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lifter.Blazor\Lifter.Blazor.csproj" />
    <ProjectReference Include="..\Lifter.Core\Lifter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

</Project>
